name: Deploy to GKE

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write' # Esto es fundamental para solicitar el token OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/57284641624/locations/global/workloadIdentityPools/zeppelin-pool/providers/github-provider'
          service_account: 'github-sa@x-radio-182800.iam.gserviceaccount.com'

      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Ahora puedes usar cualquier comando de gcloud
      - name: 'Deploy to GKE'
        run: |
          gcloud container clusters get-credentials mi-cluster --zone=us-central1-c --project=x-radio-182800
          kubectl apply -f k8s/deployment.yaml
          # Otros comandos de kubectl, etc.
